### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setProperty')

### ISSUE THREAD

**Issue by FabianDever** [ngbracket/ngx-layout#57]
Hey since using ngx-layout with angular 18 I get these erros in the console:

sentry-angular-ivy.js:135 TypeError: Cannot read properties of undefined (reading 'setProperty')
    at ngbracket-ngx-layout-core.mjs:380:41
    at Array.forEach (<anonymous>)
    at StyleUtils._applyMultiValueStyleToElement (ngbracket-ngx-layout-core.mjs:369:14)
    at StyleUtils.applyStyleToElement (ngbracket-ngx-layout-core.mjs:291:14)
    at DefaultLayoutDirective.applyStyleToElement (ngbracket-ngx-layout-core.mjs:1593:21)
    at DefaultLayoutDirective.addStyles (ngbracket-ngx-layout-core.mjs:1554:14)
    at DefaultLayoutDirective.updateWithValue (ngbracket-ngx-layout-flex.mjs:1210:18)
    at MediaMarshaller.updateElement (ngbracket-ngx-layout-core.mjs:1362:17)
    at ngbracket-ngx-layout-core.mjs:1320:26
    at Map.forEach (<anonymous>)

**Comment by DuncanFaulkner** [comment]
@FabianDever thanks for the heads up. Are you able to provide a simple stackblitz project recreating the issue, not a problem if not, will take a look.

**Comment by DuncanFaulkner** [comment]
@FabianDever is this still causing issues, recently released version 20.0.1, let me know if it is

**Comment by DuncanFaulkner** [comment]
Fix is up in #108 (targeting the `22.x.x` branch).

**Root cause:** on a media/breakpoint change (e.g. window resize), `MediaMarshaller.updateStyles()` flushes styles for every tracked element. An element can be detached/destroyed between the resize event firing and the flush, leaving `element.style` undefined — hence `Cannot read properties of undefined (reading 'setProperty')`. Because the throw aborted the whole update pass, one stale element broke styling for the rest too.

**Fix:** guard the `setProperty` call so a non-styleable element is skipped instead of throwing, plus a regression test.

@FabianDever if you're able to test against the branch and confirm it resolves the issue on Angular 18, that'd be much appreciated.

**Comment by FabianDever** [comment]
Seems to work so far, thanks a million for your help!
